Shoestore/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :categorys do
    resources :shoes
  end
  resources :admins do
    resources :shoes  
    resources :categorys
  end
  resources :categorys
  resources :shoes do
    resources :comments
  end
  resources :admins
  resources :users
  
  root 'users#index'

end

Shoestore/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    def self.search(search, page)
  		order('name').where('name LIKE ?', "%#{search}%").paginate(page: page, per_page: 3)
	end
end

Shoestore/app/models/category.rb
class Category < ActiveRecord::Base
end

Shoestore/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :shoe
end

Shoestore/app/models/shoe.rb
class Shoe < ActiveRecord::Base
  belongs_to :category
  has_many :comments
  mount_uploader :image, ImageUploader
  is_impressionable
def self.search(search, page)
  order('name').where('name LIKE ?', "%#{search}%").paginate(page: page, per_page: 3)
end
end

Shoestore/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  is_impressionable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

Shoestore/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!
	def index
		@category = Category.where(active:true)
		@shoe = Shoe.search(params[:search], params[:page])
	end
end

Shoestore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Shoestore/app/controllers/categorys_controller.rb
class CategorysController < ApplicationController
	def index
		@category = Category.all
	end
	def new
		@category = Category.new
	end
	def show
		@category = Category.find(params[:id])
		@shoe = Shoe.all
	end
	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to admins_path
		else
			render 'new'
		end
	end
	def edit
		@category = Category.find(params[:id])
	end
	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			redirect_to admins_path
		else
			render 'edit'
		end
	end
	private
	def category_params
		params.require(:category).permit(:name, :active)
	end
end

Shoestore/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
    @shoe = Shoe.find(params[:shoe_id])
    @comment = @shoe.comments.create(comment_params)
    redirect_to user_path(@shoe)
  end
	private
    def comment_params
      params.require(:comment).permit(:commenter, :content)
    end
end

Shoestore/app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
	before_action :authenticate_admin!
	impressionist :actions=>[:index, :show]
	def index
		@category = Category.all
		@shoe = Shoe.all
	end
	def show
		@shoe = Shoe.find(params[:id])
	end
	def new
		@category = Category.all
		@shoe = Shoe.new
	end
	def create
		@shoe = Shoe.new(shoe_params)
		if @shoe.save
			redirect_to admins_path
		else
			render 'new'
		end
	end
	def edit
		@category = Category.all
		@shoe = Shoe.find(params[:id])
	end
	def update
		@shoe = Shoe.find(params[:id])
		if @shoe.update(shoe_params)
			redirect_to admins_path
		else
			render 'edit'
		end
	end
	def destroy
		@shoe = Shoe.find(params[:id])
    	@shoe.destroy
    	redirect_to admins_path
	end
	private
	def shoe_params
		params.require(:shoe).permit(:name, :content, :price, :category_id, :image)
	end
end

Shoestore/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	impressionist :actions=>[:index, :show]
	def index
  		@shoe = Shoe.search(params[:search], params[:page])
  		impressionist(@shoe)
		@category = Category.all
		#@shoe = Shoe.all
	end
	def show
		@shoe = Shoe.find(params[:id])
  		impressionist(@shoe)
	end
	private
end

Shoestore/app/helpers/admins_helper.rb
module AdminsHelper
end

Shoestore/app/helpers/application_helper.rb
module ApplicationHelper
end

Shoestore/app/helpers/categorys_helper.rb
module CategorysHelper
end

Shoestore/app/helpers/comments_helper.rb
module CommentsHelper
end

Shoestore/app/helpers/shoes_helper.rb
module ShoesHelper
end

Shoestore/app/helpers/users_helper.rb
module UsersHelper
end

Shoestore/app/views/admins/index.html.erb
<% if admin_signed_in? %>
  Logged in as <strong><%= current_admin.email %></strong>.
  <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>
<h1>WELCOME TO ADMINPAGE</h1>
<p id="notice"><%= notice %></p>
<h3><%= link_to 'Category List' , categorys_path %></h3>
<br/>
<h3>Shoe List</h3>
<td><%= link_to "New Shoe" , new_shoe_path %></td>
<%= form_tag users_path, :method =>'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag 'Search', :name => nil %>
  </p>
<% end %>
<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th>Category</th>
    <th>Price</th>
    <th>View</th>
    <th>Action</th>
  </tr>
  <% @shoe.each do |s| if s.category.active==true %>
    <tr>
      <td><%= s.name %></td>
      <td><%= image_tag s.image_url.to_s %></td>
      <td><%= s.category.name %></td>
      <td><%= s.price %></td>
      <td><%=  %></td>
      <td><%= link_to "Edit" , edit_shoe_path(s) %></td>
      <td><%= link_to "Delete" , shoe_path(s) , method: :delete , data: {confirm: 'Are you sure?'} %></td>
    </tr>
    <% end %>
  <% end %>
  <%= will_paginate @shoe %>
</table>

  

Shoestore/app/views/categorys/edit.html.erb
<% if admin_signed_in? %>
  Logged in as <strong><%= current_admin.email %></strong>.
  <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>
<p id="notice"><%= notice %></p>
<%= form_for :category, url: category_path(@category.id), method: :patch do |f| %>
<% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <input type="radio" name="category[active]" value="true">Active<br>
    <input type="radio" name="category[active]" value="false" checked='<%@category.active%>'>Deactive
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Trang chu', admins_path %>

Shoestore/app/views/categorys/index.html.erb
<% if admin_signed_in? %>
  Logged in as <strong><%= current_admin.email %></strong>.
  <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>
<p id="notice"><%= notice %></p>
<h3>Category List</h3>
<td><%= link_to "New Category" , new_category_path %></td><br/>
<table>
  <tr>
    <th>Name</th>
    <th>Active</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @category.each do |c|%>
  <tr>
  <td><%= link_to c.name  %></td>
  <td><%= c.active  %></td>
  <td><%= link_to 'Edit' , edit_category_path(c.id) %></td>
  </tr>
  <% end %>
</table>
<%= link_to 'Trang chu', admins_path %>

Shoestore/app/views/categorys/new.html.erb
<% if admin_signed_in? %>
  Logged in as <strong><%= current_admin.email %></strong>.
  <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>
<p id="notice"><%= notice %></p>
<%= form_for :category, url: categorys_path do |f| %>
<% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Trang chu', admins_path %>

Shoestore/app/views/categorys/show.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<h1>WELCOME TO Shoe Store</h1>
<h3><%= @category.name%></h3>
<br/>
<h3>Shoe List</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th>Price</th>
    <th>View</th>
  </tr>
  <% @shoe.each do |s| if s.category.name==@category.name%>
    <tr>
      <td><%= link_to s.name , shoe_path(s)  %></td>
      <td><%= image_tag s.image_url.to_s %></td>
      <td><%= s.price %></td>
      <td><%=  %></td>
    </tr>
    <% end %>
  <% end %>
</table>
<%= link_to 'Trang chu' , users_path %>

  

Shoestore/app/views/layouts/admin/html/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <title>Free CSS template by ChocoTemplates.com</title>
  <link rel="stylesheet" href="css/style.css" type="text/css" media="all" />
</head>
<body>
  <div id="header">
  <div class="shell">
    <!-- Logo + Top Nav -->
    <div id="top">
      <h1><a href="/admins">Shoe Admin Page</a></h1>
      <div id="top-navigation">
        Welcome <a href="#"><strong>Administrator</strong></a>
        <span>|</span>
        <a href="#">Help</a>
        <span>|</span>
        <a href="#">Profile Settings</a>
        <span>|</span>
        <a href="#">Log out</a>
      </div>
    </div>
    <!-- End Logo + Top Nav -->
    
    <!-- Main Nav -->
    <div id="navigation">
      <ul>
          <li><a href="/admins" class="active"><span>Shoe Management</span></a></li>
          <li><a href="/categorys"><span>Category Management</span></a></li>
          <li><a href="/shoes/new"><span>New Shoe</span></a></li>
          <li><a href="/categorys/new"><span>New Category</span></a></li>
      </ul>
    </div>
    <!-- End Main Nav -->
  </div>
  </div>

  <div id="container">
  <div class="shell">
    
    <!-- Small Nav -->
    <div class="small-nav">
      <a href="#">Dashboard</a>
      <span>&gt;</span>
      Current Articles
    </div>
    <!-- End Small Nav -->
    
    <!-- Message OK -->   
    <div class="msg msg-ok">
      <p><strong>Your file was uploaded succesifully!</strong></p>
      <a href="#" class="close">close</a>
    </div>
    <!-- End Message OK -->   
    
    <!-- Message Error -->
    <div class="msg msg-error">
      <p><strong>You must select a file to upload first!</strong></p>
      <a href="#" class="close">close</a>
    </div>
    <!-- End Message Error -->
    <br />
    <!-- Main -->
    <div id="main">
      <div class="cl">&nbsp;</div>
      
      <!-- Content -->
      <div id="content">
        
        <!-- Box -->
        <div class="box">
          <!-- Box Head -->
          <div class="box-head">
            <h2 class="left">Current Articles</h2>
            <div class="right">
              <label>search articles</label>
              <input type="text" class="field small-field" />
              <input type="submit" class="button" value="search" />
            </div>
          </div>
          <!-- End Box Head --> 

          <!-- Table -->
          <div class="table">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <th>Name</th>
                <th>Category</th>
                <th>Price</th>
                <th>View</th>
                <th width="110" class="ac">Content Control</th>
              </tr>
              <% @shoe.each do |s| %>
              <tr>
                <td><%= link_to s.name , shoe_path(s)  %></td>
                <td><%= s.category.name %></td>
                <td><%= s.price %></td>
                <td><%=  %></td>
                <td><%= link_to "Edit" , edit_shoe_path(s) %>
                    <%= link_to "Delete" , shoe_path(s) , method: :delete , data: {confirm: 'Are you sure?'} %></td>
              </tr>
              <% end %>
              <tr class="odd">
                <td><input type="checkbox" class="checkbox" /></td>
                <td><h3><a href="#">Lorem ipsum dolor sit amet, consectetur.</a></h3></td>
                <td>12.05.09</td>
                <td><a href="#">Administrator</a></td>
                <td><a href="#" class="ico del">Delete</a><a href="#" class="ico edit">Edit</a></td>
              </tr>
              <tr>
                <td><input type="checkbox" class="checkbox" /></td>
                <td><h3><a href="#">Lorem ipsum dolor sit amet, consectetur.</a></h3></td>
                <td>12.05.09</td>
                <td><a href="#">Administrator</a></td>
                <td><a href="#" class="ico del">Delete</a><a href="#" class="ico edit">Edit</a></td>
              </tr>
              <tr class="odd">
                <td><input type="checkbox" class="checkbox" /></td>
                <td><h3><a href="#">Lorem ipsum dolor sit amet, consectetur.</a></h3></td>
                <td>12.05.09</td>
                <td><a href="#">Administrator</a></td>
                <td><a href="#" class="ico del">Delete</a><a href="#" class="ico edit">Edit</a></td>
              </tr>
              <tr>
                <td><input type="checkbox" class="checkbox" /></td>
                <td><h3><a href="#">Lorem ipsum dolor sit amet, consectetur.</a></h3></td>
                <td>12.05.09</td>
                <td><a href="#">Administrator</a></td>
                <td><a href="#" class="ico del">Delete</a><a href="#" class="ico edit">Edit</a></td>
              </tr>
              <tr class="odd">
                <td><input type="checkbox" class="checkbox" /></td>
                <td><h3><a href="#">Lorem ipsum dolor sit amet, consectetur.</a></h3></td>
                <td>12.05.09</td>
                <td><a href="#">Administrator</a></td>
                <td><a href="#" class="ico del">Delete</a><a href="#" class="ico edit">Edit</a></td>
              </tr>
              <tr>
                <td><input type="checkbox" class="checkbox" /></td>
                <td><h3><a href="#">Lorem ipsum dolor sit amet, consectetur.</a></h3></td>
                <td>12.05.09</td>
                <td><a href="#">Administrator</a></td>
                <td><a href="#" class="ico del">Delete</a><a href="#" class="ico edit">Edit</a></td>
              </tr>
              <tr class="odd">
                <td><input type="checkbox" class="checkbox" /></td>
                <td><h3><a href="#">Lorem ipsum dolor sit amet, consectetur.</a></h3></td>
                <td>12.05.09</td>
                <td><a href="#">Administrator</a></td>
                <td><a href="#" class="ico del">Delete</a><a href="#" class="ico edit">Edit</a></td>
              </tr>
            </table>
            
            
            <!-- Pagging -->
            <div class="pagging">
              <div class="left">Showing 1-12 of 44</div>
              <div class="right">
                <a href="#">Previous</a>
                <a href="#">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
                <a href="#">245</a>
                <span>...</span>
                <a href="#">Next</a>
                <a href="#">View all</a>
              </div>
            </div>
            <!-- End Pagging -->
            
          </div>
          <!-- Table -->
          
        </div>
        <!-- End Box -->
        
        <!-- Box -->
        <div class="box">
          <!-- Box Head -->
          <div class="box-head">
            <h2>Add New Article</h2>
          </div>
          <!-- End Box Head -->
          
          <form action="" method="post">
            
            <!-- Form -->
            <div class="form">
                <p>
                  <span class="req">max 100 symbols</span>
                  <label>Article Title <span>(Required Field)</span></label>
                  <input type="text" class="field size1" />
                </p>  
                <p class="inline-field">
                  <label>Date</label>
                  <select class="field size2">
                    <option value="">23</option>
                  </select>
                  <select class="field size3">
                    <option value="">July</option>
                  </select>
                  <select class="field size3">
                    <option value="">2009</option>
                  </select>
                </p>
                
                <p>
                  <span class="req">max 100 symbols</span>
                  <label>Content <span>(Required Field)</span></label>
                  <textarea class="field size1" rows="10" cols="30"></textarea>
                </p>  
              
            </div>
            <!-- End Form -->
            
            <!-- Form Buttons -->
            <div class="buttons">
              <input type="button" class="button" value="preview" />
              <input type="submit" class="button" value="submit" />
            </div>
            <!-- End Form Buttons -->
          </form>
        </div>
        <!-- End Box -->

      </div>
      <!-- End Content -->
      
      <!-- Sidebar -->
      <div id="sidebar">
        
        <!-- Box -->
        <div class="box">
          
          <!-- Box Head -->
          <div class="box-head">
            <h2>Management</h2>
          </div>
          <!-- End Box Head-->
          
          <div class="box-content">
            <a href="#" class="add-button"><span>Add new Article</span></a>
            <div class="cl">&nbsp;</div>
            
            <p class="select-all"><input type="checkbox" class="checkbox" /><label>select all</label></p>
            <p><a href="#">Delete Selected</a></p>
            
            <!-- Sort -->
            <div class="sort">
              <label>Sort by</label>
              <select class="field">
                <option value="">Title</option>
              </select>
              <select class="field">
                <option value="">Date</option>
              </select>
              <select class="field">
                <option value="">Author</option>
              </select>
            </div>
            <!-- End Sort -->
            
          </div>
        </div>
        <!-- End Box -->
      </div>
      <!-- End Sidebar -->
      
      <div class="cl">&nbsp;</div>      
    </div>
    <!-- Main -->
  </div>
  </div>
</body>
<h1>WELCOME TO ADMINPAGE</h1>
<h3>Category List</h3>
<td><%= link_to "New Category" , new_category_path %></td><br/>
<table>
  <tr>
    <th>Name</th>
    <th>Active</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @category.each do |c|%>
  <tr>
  <td><%= link_to c.name  %></td>
  <td><%= c.active  %></td>
  <td><%= link_to 'Edit' , edit_category_path(c.id) %></td>
  </tr>
  <% end %>
</table>
<br/>
<h3>Shoe List</h3>
<td><%= link_to "New Shoe" , new_shoe_path %></td>
<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th>Category</th>
    <th>Price</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @shoe.each do |s| %>
    <tr>
      <td><%= link_to s.name , shoe_path(s)  %></td>
      <td><%= image_tag s.image_url.to_s %></td>
      <td><%= s.category.name %></td>
      <td><%= s.price %></td>
      <td><%=  %></td>
      <td><%= link_to "Edit" , edit_shoe_path(s) %></td>
      <td><%= link_to "Delete" , shoe_path(s) , method: :delete , data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

  

Shoestore/app/views/shoes/edit.html.erb
<% if admin_signed_in? %>
  Logged in as <strong><%= current_admin.email %></strong>.
  <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>
<script type="text/javascript" src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
<script type="text/javascript" src="assets/js/jquery.uploadPreview.min.js"></script>
<p id="notice"><%= notice %></p>
<%= form_for :shoe, url: shoe_path(@shoe.id), :html => {:multipart => true}, method: :patch do |f| %>
<% if @shoe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@shoe.errors.count, "error") %> prohibited
        this shoe from being saved:
      </h2>
      <ul>
        <% @shoe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label 'Category' %><br>
    <%= f.collection_select :category_id, @category, :id, :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Trang chu', admins_path %>

Shoestore/app/views/shoes/new.html.erb
<% if admin_signed_in? %>
  Logged in as <strong><%= current_admin.email %></strong>.
  <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>
<p id="notice"><%= notice %></p>
<%= form_for :shoe, url: shoes_path, :html => {:multipart => true} do |f| %>
<% if @shoe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@shoe.errors.count, "error") %> prohibited
        this shoe from being saved:
      </h2>
      <ul>
        <% @shoe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label 'Category' %><br>
    <%= f.collection_select :category_id, @category, :id, :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Trang chu', admins_path %>

Shoestore/app/views/users/index.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<h1>WELCOME TO Shoe Store</h1>
<h3>Category List</h3>
  <% @category.each do |c| if c.active==true%>
  <td><%= link_to c.name , category_path(c.id) %></td></br>
  <% end %>
  <% end %>
<br/>
<h3>Shoe List</h3>
<%= form_tag users_path, :method =>'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag 'Search', :name => nil %>
  </p>
<% end %>
<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th>Category</th>
    <th>Price</th>
    <th>View</th>
  </tr>
  
  <% @shoe.each do |s| if s.category.active==true %>

    <tr>
      <td><%= link_to s.name , user_path(s)  %></td>
      <td><%= image_tag s.image_url.to_s %></td>
      <td><%= s.category.name %></td>
      <td><%= s.price %></td>
      <td><%= s.impressionist_count %></td>
    </tr>
    <% end %>
  <% end %>
<%= will_paginate @shoe %>
</table>

  

Shoestore/app/views/users/show.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<p>
  <strong>Name:</strong>
  <%= @shoe.name %>
</p>
 
<p>
  <%= image_tag @shoe.image_url.to_s %>
</p>

<p>
  <strong>Content:</strong>
  <%= @shoe.content %>
</p>

<p>
  <strong>Price:</strong>
  <%= @shoe.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= link_to @shoe.category.name , category_path(@shoe.category_id)%>
</p>
<p>
  <strong>View:</strong>
  <%= @shoe.impressionist_count%>
</p>
<h3>Comment</h3>
<div id="comments">
<% @shoe.comments.each do |s| %>
  <div class="comment">
  <strong><%= s.commenter %> :</strong>
    <%= s.content %>
  </div>
<% end %>
</div>


<h2>New Comment</h2>

<%= form_for([@shoe, @shoe.comments.build]) do |f| %>
  <p hidden=true>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter, :value => current_user.email%>
  </p>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>



    <tr>
      <td><%= link_to 'Trang chu' , users_path %></td>
    </tr>